const statusLines = [
  '> Engine boot: ModMind AI Generator online',
  '> Generation mode: full project scaffold',
  '> Export mode: per-file + full zip package',
  '> Systems: Mods AI and Plugins AI',
  '> Ready for production-style starter architecture'
];

const loaderOptions = {
  mods: ['fabric', 'forge', 'quilt', 'neoforge'],
  plugins: ['bukkit', 'spigot']
};

const form = document.getElementById('generatorForm');
const aiType = document.getElementById('aiType');
const loader = document.getElementById('loader');
const statusLog = document.getElementById('statusLog');
const summary = document.getElementById('summary');
const fileList = document.getElementById('fileList');
const codeView = document.getElementById('codeView');
const downloadZipBtn = document.getElementById('downloadZipBtn');
const year = document.getElementById('year');

year.textContent = new Date().getFullYear();

let latestFiles = [];
let latestProjectName = 'modmind-project';

function setLoaderOptions() {
  const nextOptions = loaderOptions[aiType.value] || [];
  loader.innerHTML = nextOptions
    .map(item => `<option value="${item}">${item[0].toUpperCase()}${item.slice(1)}</option>`)
    .join('');
}

function packageToPath(packageName) {
  return packageName.replace(/\./g, '/');
}

function selectedFeatures() {
  return Array.from(document.querySelectorAll('input[name="feature"]:checked')).map(item => item.value);
}

function sanitizeProjectName(value) {
  return value.replace(/[^a-zA-Z0-9_-]/g, '') || 'MyProject';
}

function createJavaMainClass(projectName, packageName, aiSystem, loaderName, features, theme) {
  const className = `${sanitizeProjectName(projectName).replace(/[^a-zA-Z0-9]/g, '')}Main`;
  const featureMethods = [];

  if (features.includes('commands')) {
    featureMethods.push(`    bootstrapCommandSystem();`);
  }
  if (features.includes('events')) {
    featureMethods.push(`    bootstrapEventSystem();`);
  }
  if (features.includes('config')) {
    featureMethods.push(aiSystem === 'plugins' ? `    saveDefaultConfig();` : `    bootstrapConfig();`);
  }

  if (aiSystem === 'plugins') {
    return `package ${packageName};

import ${packageName}.commands.MainCommand;
import ${packageName}.events.PlayerJoinListener;
import ${packageName}.service.FeatureService;
import org.bukkit.command.PluginCommand;
import org.bukkit.plugin.java.JavaPlugin;

public final class ${className} extends JavaPlugin {
  private FeatureService featureService;

  @Override
  public void onEnable() {
    this.featureService = new FeatureService("${theme}");
${featureMethods.join('\n')}
    getLogger().info("${projectName} enabled on ${loaderName}.");
  }

  @Override
  public void onDisable() {
    getLogger().info("${projectName} disabled.");
  }

  private void bootstrapCommandSystem() {
    PluginCommand command = getCommand("${projectName.toLowerCase()}");
    if (command != null) {
      command.setExecutor(new MainCommand(featureService));
    }
  }

  private void bootstrapEventSystem() {
    getServer().getPluginManager().registerEvents(new PlayerJoinListener(featureService), this);
  }

  private void bootstrapConfig() {
    saveDefaultConfig();
  }
}
`;
  }

  return `package ${packageName};

import ${packageName}.service.FeatureService;
import ${packageName}.registry.ModRegistry;

public class ${className} {
  private final FeatureService featureService = new FeatureService("${theme}");

  public void onInitialize() {
    ModRegistry.registerAll();
${featureMethods.join('\n')}
    System.out.println("${projectName} initialized on ${loaderName}.");
  }

  private void bootstrapCommandSystem() {
    System.out.println("Command template initialized.");
  }

  private void bootstrapEventSystem() {
    System.out.println("Event wiring template initialized.");
  }

  private void bootstrapConfig() {
    System.out.println("Config bootstrap initialized.");
  }
}
`;
}

function createMetaFile(projectName, packageName, aiSystem, loaderName) {
  const safeId = sanitizeProjectName(projectName).toLowerCase();
  const className = `${sanitizeProjectName(projectName).replace(/[^a-zA-Z0-9]/g, '')}Main`;

  if (aiSystem === 'plugins') {
    return {
      path: 'src/main/resources/plugin.yml',
      content: `name: ${projectName}
main: ${packageName}.${className}
version: 1.0.0
api-version: '1.20'
author: ModMind AI
commands:
  ${safeId}:
    description: Main command generated for ${projectName}
    usage: /${safeId}
permissions:
  ${safeId}.use:
    description: Use the ${projectName} command
    default: true
`
    };
  }

  if (loaderName === 'fabric' || loaderName === 'quilt') {
    const fileName = loaderName === 'fabric' ? 'fabric.mod.json' : 'quilt.mod.json';
    return {
      path: `src/main/resources/${fileName}`,
      content: `{
  "schemaVersion": 1,
  "id": "${safeId}",
  "version": "1.0.0",
  "name": "${projectName}",
  "description": "Generated by ModMind AI for ${loaderName}",
  "authors": ["ModMind AI"],
  "entrypoints": {
    "main": ["${packageName}.${className}"]
  },
  "depends": {
    "minecraft": ">=1.20"
  }
}`
    };
  }

  return {
    path: 'src/main/resources/META-INF/mods.toml',
    content: `modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"
[[mods]]
modId="${safeId}"
version="1.0.0"
displayName="${projectName}"
authors="ModMind AI"
description='''Generated by ModMind AI for ${loaderName}.'''
`
  };
}

function createGradleFiles(projectName, packageName, loaderName) {
  const safeName = sanitizeProjectName(projectName);
  const groupName = packageName;

  return [
    {
      path: 'settings.gradle',
      content: `rootProject.name = '${safeName}'\n`
    },
    {
      path: 'gradle.properties',
      content: `org.gradle.jvmargs=-Xmx2G\norg.gradle.daemon=false\nproject_group=${groupName}\nproject_name=${safeName}\nloader_target=${loaderName}\n`
    },
    {
      path: 'build.gradle',
      content: `plugins {
  id 'java'
}

group = '${groupName}'
version = '1.0.0'

repositories {
  mavenCentral()
}

dependencies {
  testImplementation 'junit:junit:4.13.2'
}

tasks.withType(JavaCompile).configureEach {
  options.encoding = 'UTF-8'
  options.release = 17
}
`
    }
  ];
}

function createServiceFiles(packageName, theme) {
  return [
    {
      path: `src/main/java/${packageToPath(packageName)}/service/FeatureService.java`,
      content: `package ${packageName}.service;

public class FeatureService {
  private final String theme;

  public FeatureService(String theme) {
    this.theme = theme;
  }

  public String getThemeDescription() {
    return "Project feature theme: " + theme;
  }
}
`
    },
    {
      path: `src/main/java/${packageToPath(packageName)}/registry/ModRegistry.java`,
      content: `package ${packageName}.registry;

public final class ModRegistry {
  private ModRegistry() {}

  public static void registerAll() {
    System.out.println("Registering items, blocks, and gameplay systems.");
  }
}
`
    }
  ];
}

function createFeatureFiles(projectName, packageName, aiSystem, features) {
  const safeId = sanitizeProjectName(projectName).toLowerCase();
  const files = [];

  if (features.includes('commands')) {
    files.push({
      path: `src/main/java/${packageToPath(packageName)}/commands/MainCommand.java`,
      content:
        aiSystem === 'plugins'
          ? `package ${packageName}.commands;

import ${packageName}.service.FeatureService;
import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;

public class MainCommand implements CommandExecutor {
  private final FeatureService featureService;

  public MainCommand(FeatureService featureService) {
    this.featureService = featureService;
  }

  @Override
  public boolean onCommand(CommandSender sender, Command command, String label, String[] args) {
    sender.sendMessage("[${projectName}] " + featureService.getThemeDescription());
    return true;
  }
}
`
          : `package ${packageName}.commands;

public class MainCommand {
  public String commandName() {
    return "${safeId}";
  }
}
`
    });
  }

  if (features.includes('events')) {
    files.push({
      path: `src/main/java/${packageToPath(packageName)}/events/PlayerJoinListener.java`,
      content:
        aiSystem === 'plugins'
          ? `package ${packageName}.events;

import ${packageName}.service.FeatureService;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.player.PlayerJoinEvent;

public class PlayerJoinListener implements Listener {
  private final FeatureService featureService;

  public PlayerJoinListener(FeatureService featureService) {
    this.featureService = featureService;
  }

  @EventHandler
  public void onPlayerJoin(PlayerJoinEvent event) {
    event.getPlayer().sendMessage(featureService.getThemeDescription());
  }
}
`
          : `package ${packageName}.events;

public class PlayerJoinListener {
  public void onPlayerJoin() {
    System.out.println("PlayerJoin template event handled.");
  }
}
`
    });
  }

  if (features.includes('config')) {
    files.push({
      path: 'src/main/resources/modmind-config.yml',
      content: `project:
  id: ${safeId}
  debug: false
  balancing:
    feature_multiplier: 1.0
`
    });
  }

  return files;
}

function createReadme(projectName, aiSystem, loaderName, theme, features) {
  return {
    path: 'README.md',
    content: `# ${projectName}

Generated by ModMind AI (${aiSystem} on ${loaderName}).

## Theme
${theme}

## Included systems
${features.map(item => `- ${item}`).join('\n')}

## Project structure
- Gradle build files
- Java source layout with service and registry systems
- Loader-specific metadata and config

## Next steps
1. Import into IntelliJ IDEA / Eclipse.
2. Wire generated classes into your game logic.
3. Replace placeholder logic with your finalized implementation.
`
  };
}

function buildFiles({ projectName, packageName, aiSystem, loaderName, features, theme }) {
  const className = `${sanitizeProjectName(projectName).replace(/[^a-zA-Z0-9]/g, '')}Main`;

  return [
    createReadme(projectName, aiSystem, loaderName, theme, features),
    ...createGradleFiles(projectName, packageName, loaderName),
    {
      path: `src/main/java/${packageToPath(packageName)}/${className}.java`,
      content: createJavaMainClass(projectName, packageName, aiSystem, loaderName, features, theme)
    },
    createMetaFile(projectName, packageName, aiSystem, loaderName),
    ...createServiceFiles(packageName, theme),
    ...createFeatureFiles(projectName, packageName, aiSystem, features)
  ];
}

function downloadSingleFile(file) {
  const blob = new Blob([file.content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = file.path.split('/').pop() || 'generated-file.txt';
  document.body.appendChild(link);
  link.click();
  link.remove();
  URL.revokeObjectURL(url);
}

function renderFiles(files) {
  latestFiles = files;
  fileList.innerHTML = '';

  files.forEach((file, index) => {
    const row = document.createElement('li');
    row.className = 'file-row';

    const previewButton = document.createElement('button');
    previewButton.type = 'button';
    previewButton.className = 'file-preview';
    previewButton.textContent = file.path;
    previewButton.addEventListener('click', () => {
      document.querySelectorAll('.file-preview').forEach(btn => btn.classList.remove('active'));
      previewButton.classList.add('active');
      codeView.textContent = file.content;
    });

    const downloadButton = document.createElement('button');
    downloadButton.type = 'button';
    downloadButton.className = 'file-download';
    downloadButton.textContent = '↓';
    downloadButton.title = `Download ${file.path}`;
    downloadButton.addEventListener('click', () => downloadSingleFile(file));

    if (index === 0) {
      previewButton.classList.add('active');
      codeView.textContent = file.content;
    }

    row.appendChild(previewButton);
    row.appendChild(downloadButton);
    fileList.appendChild(row);
  });

  downloadZipBtn.disabled = files.length === 0;
}

async function downloadZipBundle() {
  if (!latestFiles.length) return;

  if (!window.JSZip) {
    summary.classList.remove('muted');
    summary.textContent = 'Zip library failed to load. Check your internet connection and reload page.';
    return;
  }

  const zip = new window.JSZip();
  latestFiles.forEach(file => {
    zip.file(file.path, file.content);
  });

  const blob = await zip.generateAsync({ type: 'blob' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `${latestProjectName}.zip`;
  document.body.appendChild(link);
  link.click();
  link.remove();
  URL.revokeObjectURL(url);
}

function validatePackageName(packageName) {
  return /^[a-z][a-z0-9_]*(\.[a-z][a-z0-9_]*)+$/.test(packageName);
}

function runGeneration(event) {
  event.preventDefault();
  const projectName = document.getElementById('projectName').value.trim();
  const packageName = document.getElementById('packageName').value.trim();
  const theme = document.getElementById('featureTheme').value.trim();
  const aiSystem = aiType.value;
  const loaderName = loader.value;
  const features = selectedFeatures();

  if (!projectName) {
    summary.textContent = 'Please enter a project name.';
    summary.classList.remove('muted');
    return;
  }

  if (!validatePackageName(packageName)) {
    summary.textContent = 'Package name must look like: dev.modmind.project';
    summary.classList.remove('muted');
    return;
  }

  if (!theme) {
    summary.textContent = 'Please enter a feature theme.';
    summary.classList.remove('muted');
    return;
  }

  if (!features.length) {
    summary.textContent = 'Select at least one feature (commands/events/config).';
    summary.classList.remove('muted');
    return;
  }

  latestProjectName = sanitizeProjectName(projectName).toLowerCase();
  const files = buildFiles({ projectName, packageName, aiSystem, loaderName, features, theme });
  renderFiles(files);
  summary.classList.add('muted');
  summary.textContent = `Generated ${files.length} files for ${projectName} (${aiSystem} • ${loaderName}) with zip export ready.`;
}

function animateStatus() {
  let line = 0;
  function tick() {
    if (line === 0) statusLog.textContent = '';
    statusLog.textContent += `${statusLines[line]}\n`;
    line += 1;
    if (line >= statusLines.length) line = 0;
    setTimeout(tick, 1400);
  }
  tick();
}

function initRevealAnimations() {
  const observer = new IntersectionObserver(
    entries => {
      entries.forEach(entry => {
        if (entry.isIntersecting) entry.target.classList.add('show');
      });
    },
    { threshold: 0.15 }
  );

  document.querySelectorAll('.reveal').forEach(el => observer.observe(el));
}

aiType.addEventListener('change', setLoaderOptions);
form.addEventListener('submit', runGeneration);
downloadZipBtn.addEventListener('click', downloadZipBundle);

setLoaderOptions();
animateStatus();
initRevealAnimations();
