const statusLines = [
  '> Engine boot: ModMind AI Generator online',
  '> Local generation mode: ACTIVE',
  '> Available systems: Mods AI + Plugins AI',
  '> Available loaders: Fabric, Forge, Quilt, NeoForge, Bukkit, Spigot',
  '> Ready to build complete starter projects'
];

const loaderOptions = {
  mods: ['fabric', 'forge', 'quilt', 'neoforge'],
  plugins: ['bukkit', 'spigot']
};

const form = document.getElementById('generatorForm');
const aiType = document.getElementById('aiType');
const loader = document.getElementById('loader');
const statusLog = document.getElementById('statusLog');
const summary = document.getElementById('summary');
const fileList = document.getElementById('fileList');
const codeView = document.getElementById('codeView');
const downloadBtn = document.getElementById('downloadBtn');
const year = document.getElementById('year');

year.textContent = new Date().getFullYear();

let latestFiles = [];

function setLoaderOptions() {
  const nextOptions = loaderOptions[aiType.value] || [];
  loader.innerHTML = nextOptions
    .map(item => `<option value="${item}">${item[0].toUpperCase()}${item.slice(1)}</option>`)
    .join('');
}

function packageToPath(packageName) {
  return packageName.replace(/\./g, '/');
}

function selectedFeatures() {
  return Array.from(document.querySelectorAll('input[name="feature"]:checked')).map(item => item.value);
}

function createJavaMainClass(projectName, packageName, aiSystem, loaderName, features) {
  const className = `${projectName.replace(/[^a-zA-Z0-9]/g, '')}Main`;
  const header = `package ${packageName};\n\n`;
  const intro =
    aiSystem === 'plugins'
      ? `import org.bukkit.plugin.java.JavaPlugin;\n\npublic final class ${className} extends JavaPlugin {\n`
      : `public class ${className} {\n`;

  const startMethod =
    aiSystem === 'plugins'
      ? `  @Override\n  public void onEnable() {\n    getLogger().info("${projectName} plugin enabled on ${loaderName}.");\n`
      : `  public void onInitialize() {\n    System.out.println("${projectName} mod initialized on ${loaderName}.");\n`;

  const featureLines = [];
  if (features.includes('commands')) {
    featureLines.push(
      aiSystem === 'plugins'
        ? '    getLogger().info("Command registration template loaded.");'
        : '    System.out.println("Command registration template loaded.");'
    );
  }
  if (features.includes('events')) {
    featureLines.push(
      aiSystem === 'plugins'
        ? '    getLogger().info("Event listener template loaded.");'
        : '    System.out.println("Event listener template loaded.");'
    );
  }
  if (features.includes('config')) {
    featureLines.push(
      aiSystem === 'plugins'
        ? '    saveDefaultConfig();'
        : '    System.out.println("Config bootstrap template loaded.");'
    );
  }

  const endMethod = aiSystem === 'plugins' ? '  }\n\n  @Override\n  public void onDisable() {\n    getLogger().info("Plugin disabled.");\n  }\n}\n' : '  }\n}\n';

  return `${header}${intro}${startMethod}${featureLines.join('\n')}\n${endMethod}`;
}

function createMetaFile(projectName, packageName, aiSystem, loaderName) {
  if (aiSystem === 'plugins') {
    return {
      path: 'src/main/resources/plugin.yml',
      content: `name: ${projectName}\nmain: ${packageName}.${projectName.replace(/[^a-zA-Z0-9]/g, '')}Main\nversion: 1.0.0\napi-version: '1.20'\ncommands:\n  ${projectName.toLowerCase()}:\n    description: Base command generated by ModMind AI\n`
    };
  }

  if (loaderName === 'fabric' || loaderName === 'quilt') {
    const fileName = loaderName === 'fabric' ? 'fabric.mod.json' : 'quilt.mod.json';
    return {
      path: `src/main/resources/${fileName}`,
      content: `{
  "schemaVersion": 1,
  "id": "${projectName.toLowerCase()}",
  "version": "1.0.0",
  "name": "${projectName}",
  "description": "Generated by ModMind AI for ${loaderName}",
  "entrypoints": {
    "main": ["${packageName}.${projectName.replace(/[^a-zA-Z0-9]/g, '')}Main"]
  }
}`
    };
  }

  return {
    path: 'src/main/resources/META-INF/mods.toml',
    content: `modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"
[[mods]]
modId="${projectName.toLowerCase()}"
version="1.0.0"
displayName="${projectName}"
description='''Generated by ModMind AI for ${loaderName}.'''
`
  };
}

function buildFiles({ projectName, packageName, aiSystem, loaderName, features }) {
  const safeName = projectName.replace(/[^a-zA-Z0-9_-]/g, '') || 'MyProject';
  const packagePath = packageToPath(packageName);
  const className = `${safeName.replace(/[^a-zA-Z0-9]/g, '')}Main`;

  const files = [
    {
      path: `README-${safeName}.md`,
      content: `# ${projectName}\n\nGenerated by ModMind AI (${aiSystem} on ${loaderName}).\n\n## Included features\n- ${features.join('\n- ')}\n\n## Next step\nOpen this project in your IDE and hook these templates into your game/server runtime.\n`
    },
    {
      path: `src/main/java/${packagePath}/${className}.java`,
      content: createJavaMainClass(projectName, packageName, aiSystem, loaderName, features)
    },
    createMetaFile(projectName, packageName, aiSystem, loaderName)
  ];

  if (features.includes('config')) {
    files.push({
      path: 'src/main/resources/modmind-config.properties',
      content: `# Generated config\nenabled=true\nloader=${loaderName}\nmode=${aiSystem}\n`
    });
  }

  if (features.includes('commands')) {
    files.push({
      path: `src/main/java/${packagePath}/commands/BaseCommand.java`,
      content: `package ${packageName}.commands;\n\npublic class BaseCommand {\n  public String getName() {\n    return "${projectName.toLowerCase()}";\n  }\n}\n`
    });
  }

  if (features.includes('events')) {
    files.push({
      path: `src/main/java/${packagePath}/events/BaseEvents.java`,
      content: `package ${packageName}.events;\n\npublic class BaseEvents {\n  public void register() {\n    System.out.println("Event template ready.");\n  }\n}\n`
    });
  }

  return files;
}

function renderFiles(files) {
  latestFiles = files;
  fileList.innerHTML = '';

  files.forEach((file, index) => {
    const item = document.createElement('li');
    const button = document.createElement('button');
    button.type = 'button';
    button.textContent = file.path;
    button.addEventListener('click', () => {
      document.querySelectorAll('.file-list button').forEach(btn => btn.classList.remove('active'));
      button.classList.add('active');
      codeView.textContent = file.content;
    });

    if (index === 0) {
      button.classList.add('active');
      codeView.textContent = file.content;
    }

    item.appendChild(button);
    fileList.appendChild(item);
  });

  downloadBtn.disabled = files.length === 0;
}

function downloadBundle() {
  if (!latestFiles.length) return;
  const merged = latestFiles.map(file => `=== ${file.path} ===\n${file.content}`).join('\n\n');
  const blob = new Blob([merged], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = 'modmind-generated-bundle.txt';
  document.body.appendChild(link);
  link.click();
  link.remove();
  URL.revokeObjectURL(url);
}

function validatePackageName(packageName) {
  return /^[a-z][a-z0-9_]*(\.[a-z][a-z0-9_]*)+$/.test(packageName);
}

function runGeneration(event) {
  event.preventDefault();
  const projectName = document.getElementById('projectName').value.trim();
  const packageName = document.getElementById('packageName').value.trim();
  const aiSystem = aiType.value;
  const loaderName = loader.value;
  const features = selectedFeatures();

  if (!projectName) {
    summary.textContent = 'Please enter a project name.';
    summary.classList.remove('muted');
    return;
  }

  if (!validatePackageName(packageName)) {
    summary.textContent = 'Package name must look like: dev.modmind.project';
    summary.classList.remove('muted');
    return;
  }

  if (!features.length) {
    summary.textContent = 'Select at least one feature (commands/events/config).';
    summary.classList.remove('muted');
    return;
  }

  const files = buildFiles({ projectName, packageName, aiSystem, loaderName, features });
  renderFiles(files);
  summary.classList.add('muted');
  summary.textContent = `Generated ${files.length} files for ${projectName} (${aiSystem} • ${loaderName}).`;
}

function animateStatus() {
  let line = 0;
  function tick() {
    if (line === 0) statusLog.textContent = '';
    statusLog.textContent += `${statusLines[line]}\n`;
    line += 1;
    if (line >= statusLines.length) line = 0;
    setTimeout(tick, 1400);
  }
  tick();
}

function initRevealAnimations() {
  const observer = new IntersectionObserver(
    entries => {
      entries.forEach(entry => {
        if (entry.isIntersecting) entry.target.classList.add('show');
      });
    },
    { threshold: 0.15 }
  );

  document.querySelectorAll('.reveal').forEach(el => observer.observe(el));
}

aiType.addEventListener('change', setLoaderOptions);
form.addEventListener('submit', runGeneration);
downloadBtn.addEventListener('click', downloadBundle);

setLoaderOptions();
animateStatus();
initRevealAnimations();
